---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: upload-app
  namespace: sample-video-coding-ns
spec:
  selector:
    matchLabels:
      app: upload-app
  template:
    metadata:
      labels:
        app: upload-app
    spec:
      containers:
      - name: upload-app
        image: cloudmedialab/upload-tomcat-service:2.0
        env:
          - name: SERVICE_PORT
            value: "8080"
          - name: BASE_URL
            value: "/upload"
          - name: HEALTH_PATH
            value: "/health"
          - name: METRICS_PATH
            value: "/metrics"
          - name: LOG_LEVEL
            value: "DEBUG"
          - name: GET_ENABLED
            value: "true"
            # Max size in MB of the body in the request
          - name: MAX_REQUEST_THRESHOLD
            value: "10"
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: upload-service
  namespace: sample-video-coding-ns
spec:
  type: ClusterIP
  selector:
    app: upload-app
  ports:
  - port: 80
    targetPort: 8080
